# SPDX-License-Identifier: GPL-2.0-only
# Makefile for PicoCalc Linux drivers.
# 24 May 2025, Mark Birss, <mailto:markbirss@gmail.com>

obj-$(CONFIG_PICOCALC_KBD)      	   += picocalc_kbd.o
obj-$(CONFIG_PICOCALC_SND_PWM)             += picocalc_snd_pwm.o
obj-$(CONFIG_PICOCALC_SND_SOFTPWM)         += picocalc_snd_softpwm.o
